CREATE TABLE core.oidc_user_identities (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES core.users(id) ON DELETE CASCADE,
  issuer text NOT NULL,
  subject text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT oidc_user_identities_issuer_subject_key UNIQUE (issuer, subject)
);

CREATE INDEX oidc_user_identities_user_id_idx
  ON core.oidc_user_identities (user_id);
