/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/oidc/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDCログインを開始する */
        get: {
            parameters: {
                query?: {
                    returnTo?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Browser redirect to the identity provider or the frontend. */
                303: {
                    headers: {
                        LOCATION: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDCログインのcallbackを処理する */
        get: {
            parameters: {
                query?: {
                    code?: string;
                    state?: string;
                    error?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Browser redirect to the identity provider or the frontend. */
                303: {
                    headers: {
                        LOCATION: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 認証設定の公開情報を取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["AuthConfigInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** セッションを取得する */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["SessionInfo"];
                    };
                };
            };
        };
        put?: never;
        /**
         * 新規セッションを発行する
         * @description テスト用のセッションを発行する。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["CreateSession"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["SessionInfo"];
                    };
                };
            };
        };
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{worldSlug}/changesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 公開済みのChangeset一覧を取得する
         * @description published状態のChangesetをIDの降順で返す。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Changeset"][];
                    };
                };
            };
        };
        put?: never;
        /**
         * Changesetを作成する
         * @description 認証中のユーザーを所有者として、編集内容を一時保存するopen状態のChangesetを作成する。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["ChangesetInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Changeset"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{worldSlug}/changesets/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changesetを公開する
         * @description 認証中のユーザーが所有するopen状態のChangesetを検証し、Draftの編集内容を一括で公開する。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Changeset"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{worldSlug}/changesets/{id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changesetを破棄する
         * @description 認証中のユーザーが所有するopen状態のChangesetからDraftを削除し、abandoned状態に変更する。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{worldSlug}/nodes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Nodeを取得する
         * @description 指定したIDの公開済みかつ削除されていないNodeを返す。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Nodeを削除する
         * @description expectedVersionを検証し、指定したChangesetにNodeの削除をDraftとして保存する。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["DeleteInput"];
                };
            };
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Nodeを更新する
         * @description expectedVersionを検証し、Nodeの座標とタグを指定したChangesetのDraftに保存する。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["NodePatch"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["IdVersion"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/worlds/{worldSlug}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Nodeを作成する
         * @description 認証中のユーザーが所有するopen状態のChangesetに、新しいNodeをDraftとして追加する。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["NodeInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["IdVersion"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{worldSlug}/ways/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Wayを取得する
         * @description 指定したIDの公開済みかつ削除されていないWayを、順序付けされたNode参照とともに返す。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Wayを削除する
         * @description expectedVersionを検証し、指定したChangesetにWayの削除をDraftとして保存する。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["DeleteInput"];
                };
            };
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Wayを更新する
         * @description expectedVersion、Node参照、geometryKindを検証し、Wayの内容を指定したChangesetのDraftに保存する。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["WayPatch"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["IdVersion"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/worlds/{worldSlug}/ways": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Wayを作成する
         * @description Node参照とgeometryKindを検証し、指定したChangesetに新しいWayをDraftとして追加する。geometryKindはlineまたはareaを指定する。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["WayInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["IdVersion"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{worldSlug}/relations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Relationを取得する
         * @description 指定したIDの公開済みかつ削除されていないRelationを返す。メンバーはレスポンスに含まれない。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Relationを削除する
         * @description expectedVersionを検証し、指定したChangesetにRelationの削除をDraftとして保存する。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["DeleteInput"];
                };
            };
            responses: {
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Relationを更新する
         * @description expectedVersionとWayメンバーを検証し、multipolygon Relationの内容を指定したChangesetのDraftに保存する。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["RelationPatch"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["IdVersion"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/worlds/{worldSlug}/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Relationを作成する
         * @description Wayメンバーを検証し、指定したChangesetに新しいmultipolygon RelationをDraftとして追加する。メンバーのroleにはouter、inner、または未指定を使用できる。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["RelationInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["IdVersion"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{worldSlug}/viewport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Viewport内の地物を取得する
         * @description bboxに`minX,minZ,maxX,maxZ`を指定し、範囲内のNodeとWay、およびWayが参照するNodeを返す。includeRelationsがtrueの場合は、範囲と交差するRelationとそのメンバーも含める。
         */
        get: {
            parameters: {
                query: {
                    bbox: string;
                    includeRelations?: boolean;
                };
                header?: never;
                path: {
                    worldSlug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["Viewport"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up a public user by user ID. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["User"];
                    };
                };
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["World"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json; charset=utf-8": components["schemas"]["WorldInput"];
                };
            };
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["World"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worlds/{worldSlug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    worldSlug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json; charset=utf-8": components["schemas"]["World"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthConfigInfo */
        AuthConfigInfo: {
            oidcEnabled: boolean;
            developerAuthEnabled: boolean;
        };
        /** Changeset */
        Changeset: {
            /** Format: int64 */
            id: number;
            status: components["schemas"]["ChangesetStatus"];
            comment: string | null;
            createdBy: components["schemas"]["User"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            publishedAt: string | null;
        };
        /** ChangesetInput */
        ChangesetInput: {
            comment?: string;
        };
        /** @enum {string} */
        ChangesetStatus: "open" | "published" | "abandoned";
        /** CreateSession */
        CreateSession: {
            userId: string;
        };
        /** DeleteInput */
        DeleteInput: {
            /** Format: int64 */
            changesetId: number;
            /** Format: int32 */
            expectedVersion: number;
        };
        /** @enum {string} */
        GeometryKind: "line" | "area";
        /** IdVersion */
        IdVersion: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            version: number;
        };
        /** NodeInput */
        NodeInput: {
            /** Format: int64 */
            changesetId: number;
            geom: components["schemas"]["Point"];
            tags: {
                [key: string]: string;
            };
        };
        /** NodePatch */
        NodePatch: {
            /** Format: int64 */
            changesetId: number;
            /** Format: int32 */
            expectedVersion: number;
            geom: components["schemas"]["Point"];
            tags: {
                [key: string]: string;
            };
        };
        /** Point */
        Point: {
            /** Format: double */
            x: number;
            /** Format: double */
            y: number;
            /** Format: double */
            z: number;
        };
        /** RelationInput */
        RelationInput: {
            /** Format: int64 */
            changesetId: number;
            relationType: string;
            members: components["schemas"]["RelationMember"][];
            tags: {
                [key: string]: string;
            };
        };
        /** RelationMember */
        RelationMember: {
            memberType: string;
            /** Format: int64 */
            memberId: number;
            role?: string;
        };
        /** RelationPatch */
        RelationPatch: {
            /** Format: int64 */
            changesetId: number;
            /** Format: int32 */
            expectedVersion: number;
            relationType: string;
            members: components["schemas"]["RelationMember"][];
            tags: {
                [key: string]: string;
            };
        };
        /**
         * SessionInfo
         * @description 新規セッションの内容
         */
        SessionInfo: {
            user: (components["schemas"]["User"] & unknown) | null;
        };
        /** User */
        User: {
            /** Format: int64 */
            id: number;
            userId: string;
            username: string;
        };
        /** Viewport */
        Viewport: {
            nodes: components["schemas"]["ViewportNode"][];
            ways: components["schemas"]["ViewportWay"][];
            wayNodes: components["schemas"]["ViewportWayNode"][];
            relations: components["schemas"]["ViewportRelation"][];
            relationMembers: components["schemas"]["ViewportRelationMember"][];
        };
        /** ViewportNode */
        ViewportNode: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            version: number;
            geom: components["schemas"]["Point"];
            tags: {
                [key: string]: string;
            };
            /** Format: date-time */
            deletedAt: string | null;
            /** Format: int64 */
            changesetId: number;
        };
        /** ViewportRelation */
        ViewportRelation: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            version: number;
            relationType: string;
            tags: {
                [key: string]: string;
            };
            /** Format: date-time */
            deletedAt: string | null;
            /** Format: int64 */
            changesetId: number;
        };
        /** ViewportRelationMember */
        ViewportRelationMember: {
            /** Format: int64 */
            relationId: number;
            /** Format: int32 */
            seq: number;
            memberType: string;
            /** Format: int64 */
            memberId: number;
            role: string | null;
            /** Format: int64 */
            changesetId: number;
        };
        /** ViewportWay */
        ViewportWay: {
            /** Format: int64 */
            id: number;
            /** Format: int32 */
            version: number;
            geometryKind: components["schemas"]["GeometryKind"];
            tags: {
                [key: string]: string;
            };
            isClosed: boolean;
            /** Format: date-time */
            deletedAt: string | null;
            /** Format: int64 */
            changesetId: number;
        };
        /** ViewportWayNode */
        ViewportWayNode: {
            /** Format: int64 */
            wayId: number;
            /** Format: int32 */
            seq: number;
            /** Format: int64 */
            nodeId: number;
            /** Format: int64 */
            changesetId: number;
        };
        /** WayInput */
        WayInput: {
            /** Format: int64 */
            changesetId: number;
            geometryKind: components["schemas"]["GeometryKind"];
            nodeRefs: number[];
            tags: {
                [key: string]: string;
            };
        };
        /** WayPatch */
        WayPatch: {
            /** Format: int64 */
            changesetId: number;
            /** Format: int32 */
            expectedVersion: number;
            geometryKind: components["schemas"]["GeometryKind"];
            nodeRefs: number[];
            tags: {
                [key: string]: string;
            };
        };
        /** World */
        World: {
            /** Format: int64 */
            id: number;
            slug: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: components["schemas"]["User"];
        };
        /** WorldInput */
        WorldInput: {
            slug: string;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
