CREATE EXTENSION IF NOT EXISTS postgis;

CREATE SCHEMA IF NOT EXISTS core;
CREATE SCHEMA IF NOT EXISTS draft;
CREATE SCHEMA IF NOT EXISTS history;
CREATE SCHEMA IF NOT EXISTS derived;

CREATE SEQUENCE core.node_id_seq AS bigint;
CREATE SEQUENCE core.way_id_seq AS bigint;
CREATE SEQUENCE core.relation_id_seq AS bigint;

CREATE OR REPLACE FUNCTION core.catlas_are_string_tags(input jsonb)
RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
  SELECT jsonb_typeof(input) = 'object'
    AND NOT EXISTS (
      SELECT 1 FROM jsonb_each(input) AS tag_entry(key, value)
      WHERE jsonb_typeof(value) <> 'string'
    );
$$;

CREATE OR REPLACE FUNCTION core.catlas_has_no_reserved_tag_keys(input jsonb)
RETURNS boolean LANGUAGE sql IMMUTABLE AS $$
  SELECT NOT EXISTS (
    SELECT 1 FROM jsonb_object_keys(input) AS key_name
    WHERE key_name = ANY (ARRAY[
      'feature_type', 'relation_type', 'geometry_kind', 'is_closed',
      'version', 'deleted_at', 'changeset_id'
    ])
  );
$$;

CREATE TABLE core.changesets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status text NOT NULL CHECK (status IN ('open', 'published', 'abandoned')),
  comment text,
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz,
  CONSTRAINT changesets_published_at_matches_status CHECK (
    (status = 'published') = (published_at IS NOT NULL)
  )
);

-- Published entities. Draft mutations never live in these tables.
CREATE TABLE core.nodes (
  id bigint NOT NULL DEFAULT nextval('core.node_id_seq') PRIMARY KEY,
  mc_x double precision NOT NULL,
  mc_y double precision NOT NULL, mc_z double precision NOT NULL,
  geom_2d geometry(Point, 0) GENERATED ALWAYS AS
    (ST_SetSRID(ST_MakePoint(mc_x, mc_z), 0)) STORED,
  feature_type text NOT NULL, tags jsonb NOT NULL DEFAULT '{}'::jsonb,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(), created_by text NOT NULL,
  updated_by text NOT NULL, deleted_at timestamptz,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  CONSTRAINT nodes_tags_are_string_map CHECK (core.catlas_are_string_tags(tags)),
  CONSTRAINT nodes_tags_have_no_reserved_keys CHECK (core.catlas_has_no_reserved_tag_keys(tags))
);

CREATE TABLE core.ways (
  id bigint NOT NULL DEFAULT nextval('core.way_id_seq') PRIMARY KEY,
  feature_type text NOT NULL,
  geometry_kind text NOT NULL CHECK (geometry_kind IN ('line', 'area')),
  is_closed boolean NOT NULL DEFAULT false, tags jsonb NOT NULL DEFAULT '{}'::jsonb,
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL, updated_by text NOT NULL, deleted_at timestamptz,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  CONSTRAINT ways_tags_are_string_map CHECK (core.catlas_are_string_tags(tags)),
  CONSTRAINT ways_tags_have_no_reserved_keys CHECK (core.catlas_has_no_reserved_tag_keys(tags))
);

CREATE TABLE core.way_nodes (
  way_id bigint NOT NULL REFERENCES core.ways(id),
  seq integer NOT NULL CHECK (seq >= 0),
  node_id bigint NOT NULL REFERENCES core.nodes(id),
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  PRIMARY KEY (way_id, seq)
);

CREATE TABLE core.relations (
  id bigint NOT NULL DEFAULT nextval('core.relation_id_seq') PRIMARY KEY,
  relation_type text NOT NULL,
  tags jsonb NOT NULL DEFAULT '{}'::jsonb, version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  created_by text NOT NULL, updated_by text NOT NULL, deleted_at timestamptz,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  CONSTRAINT relations_tags_are_string_map CHECK (core.catlas_are_string_tags(tags)),
  CONSTRAINT relations_tags_have_no_reserved_keys CHECK (core.catlas_has_no_reserved_tag_keys(tags))
);

CREATE TABLE core.relation_members (
  relation_id bigint NOT NULL REFERENCES core.relations(id),
  member_type text NOT NULL CHECK (member_type IN ('node', 'way', 'relation')),
  member_id bigint NOT NULL, seq integer NOT NULL CHECK (seq >= 0), role text,
  changeset_id bigint NOT NULL REFERENCES core.changesets(id),
  PRIMARY KEY (relation_id, seq)
);

ALTER SEQUENCE core.node_id_seq OWNED BY core.nodes.id;
ALTER SEQUENCE core.way_id_seq OWNED BY core.ways.id;
ALTER SEQUENCE core.relation_id_seq OWNED BY core.relations.id;

-- Parent rows are complete proposed states. Child rows below are complete
-- ordered lists for their staged parent.
CREATE TABLE draft.nodes (
  changeset_id bigint NOT NULL REFERENCES core.changesets(id) ON DELETE CASCADE,
  id bigint NOT NULL,
  operation text NOT NULL CHECK (operation IN ('create', 'update', 'delete')),
  base_version integer,
  mc_x double precision, mc_y double precision, mc_z double precision,
  feature_type text, tags jsonb,
  staged_by text NOT NULL, staged_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (changeset_id, id),
  CONSTRAINT draft_nodes_base_version CHECK (
    (operation = 'create' AND base_version IS NULL)
    OR (operation IN ('update', 'delete') AND base_version > 0)
  ),
  CONSTRAINT draft_nodes_fields CHECK (
    operation = 'delete'
    OR (
      mc_x IS NOT NULL AND mc_y IS NOT NULL AND mc_z IS NOT NULL
      AND feature_type IS NOT NULL AND tags IS NOT NULL
      AND core.catlas_are_string_tags(tags)
      AND core.catlas_has_no_reserved_tag_keys(tags)
    )
  )
);

CREATE TABLE draft.ways (
  changeset_id bigint NOT NULL REFERENCES core.changesets(id) ON DELETE CASCADE,
  id bigint NOT NULL,
  operation text NOT NULL CHECK (operation IN ('create', 'update', 'delete')),
  base_version integer, feature_type text, geometry_kind text, is_closed boolean, tags jsonb,
  staged_by text NOT NULL, staged_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (changeset_id, id),
  CONSTRAINT draft_ways_base_version CHECK (
    (operation = 'create' AND base_version IS NULL)
    OR (operation IN ('update', 'delete') AND base_version > 0)
  ),
  CONSTRAINT draft_ways_fields CHECK (
    operation = 'delete'
    OR (
      feature_type IS NOT NULL AND geometry_kind IN ('line', 'area')
      AND is_closed IS NOT NULL AND tags IS NOT NULL
      AND core.catlas_are_string_tags(tags)
      AND core.catlas_has_no_reserved_tag_keys(tags)
    )
  )
);

CREATE TABLE draft.way_nodes (
  changeset_id bigint NOT NULL,
  way_id bigint NOT NULL,
  seq integer NOT NULL CHECK (seq >= 0),
  node_id bigint NOT NULL,
  PRIMARY KEY (changeset_id, way_id, seq),
  FOREIGN KEY (changeset_id, way_id)
    REFERENCES draft.ways (changeset_id, id) ON DELETE CASCADE
);

CREATE TABLE draft.relations (
  changeset_id bigint NOT NULL REFERENCES core.changesets(id) ON DELETE CASCADE,
  id bigint NOT NULL,
  operation text NOT NULL CHECK (operation IN ('create', 'update', 'delete')),
  base_version integer, relation_type text, tags jsonb,
  staged_by text NOT NULL, staged_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (changeset_id, id),
  CONSTRAINT draft_relations_base_version CHECK (
    (operation = 'create' AND base_version IS NULL)
    OR (operation IN ('update', 'delete') AND base_version > 0)
  ),
  CONSTRAINT draft_relations_fields CHECK (
    operation = 'delete'
    OR (
      relation_type IS NOT NULL AND tags IS NOT NULL
      AND core.catlas_are_string_tags(tags)
      AND core.catlas_has_no_reserved_tag_keys(tags)
    )
  )
);

CREATE TABLE draft.relation_members (
  changeset_id bigint NOT NULL,
  relation_id bigint NOT NULL,
  seq integer NOT NULL CHECK (seq >= 0),
  member_type text NOT NULL CHECK (member_type IN ('node', 'way', 'relation')),
  member_id bigint NOT NULL,
  role text,
  PRIMARY KEY (changeset_id, relation_id, seq),
  FOREIGN KEY (changeset_id, relation_id)
    REFERENCES draft.relations (changeset_id, id) ON DELETE CASCADE
);

CREATE OR REPLACE FUNCTION draft.catlas_require_open_changeset()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM core.changesets
    WHERE id = NEW.changeset_id AND status = 'open'
  ) THEN
    RAISE EXCEPTION 'draft mutation requires an open changeset: %', NEW.changeset_id;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER draft_nodes_require_open_changeset
  BEFORE INSERT OR UPDATE ON draft.nodes
  FOR EACH ROW EXECUTE FUNCTION draft.catlas_require_open_changeset();
CREATE TRIGGER draft_ways_require_open_changeset
  BEFORE INSERT OR UPDATE ON draft.ways
  FOR EACH ROW EXECUTE FUNCTION draft.catlas_require_open_changeset();
CREATE TRIGGER draft_way_nodes_require_open_changeset
  BEFORE INSERT OR UPDATE ON draft.way_nodes
  FOR EACH ROW EXECUTE FUNCTION draft.catlas_require_open_changeset();
CREATE TRIGGER draft_relations_require_open_changeset
  BEFORE INSERT OR UPDATE ON draft.relations
  FOR EACH ROW EXECUTE FUNCTION draft.catlas_require_open_changeset();
CREATE TRIGGER draft_relation_members_require_open_changeset
  BEFORE INSERT OR UPDATE ON draft.relation_members
  FOR EACH ROW EXECUTE FUNCTION draft.catlas_require_open_changeset();

CREATE TABLE derived.way_geometries (
  way_id bigint PRIMARY KEY REFERENCES core.ways(id), geom geometry NOT NULL,
  bbox geometry NOT NULL, source_version integer NOT NULL,
  refreshed_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE derived.relation_geometries (
  relation_id bigint PRIMARY KEY REFERENCES core.relations(id), geom geometry NOT NULL,
  bbox geometry NOT NULL, source_version integer NOT NULL,
  refreshed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE history.node_versions (
  node_id bigint NOT NULL, version integer NOT NULL CHECK (version > 0),
  snapshot jsonb NOT NULL, changeset_id bigint NOT NULL REFERENCES core.changesets(id), recorded_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (node_id, version)
);
CREATE TABLE history.way_versions (
  way_id bigint NOT NULL, version integer NOT NULL CHECK (version > 0),
  snapshot jsonb NOT NULL, changeset_id bigint NOT NULL REFERENCES core.changesets(id), recorded_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (way_id, version)
);
CREATE TABLE history.way_node_versions (
  way_id bigint NOT NULL, parent_version integer NOT NULL CHECK (parent_version > 0),
  seq integer NOT NULL CHECK (seq >= 0),
  snapshot jsonb NOT NULL, changeset_id bigint NOT NULL REFERENCES core.changesets(id), recorded_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (way_id, parent_version, seq)
);
CREATE TABLE history.relation_versions (
  relation_id bigint NOT NULL, version integer NOT NULL CHECK (version > 0),
  snapshot jsonb NOT NULL, changeset_id bigint NOT NULL REFERENCES core.changesets(id), recorded_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (relation_id, version)
);
CREATE TABLE history.relation_member_versions (
  relation_id bigint NOT NULL, parent_version integer NOT NULL CHECK (parent_version > 0),
  seq integer NOT NULL CHECK (seq >= 0),
  snapshot jsonb NOT NULL, changeset_id bigint NOT NULL REFERENCES core.changesets(id), recorded_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (relation_id, parent_version, seq)
);

CREATE INDEX nodes_geom_2d_gist_idx ON core.nodes USING gist (geom_2d);
CREATE INDEX way_nodes_node_id_idx ON core.way_nodes (node_id);
CREATE INDEX relation_members_relation_id_seq_idx ON core.relation_members (relation_id, seq);
CREATE INDEX relation_members_member_idx ON core.relation_members (member_type, member_id);
CREATE INDEX way_geometries_geom_gist_idx ON derived.way_geometries USING gist (geom);
CREATE INDEX relation_geometries_geom_gist_idx ON derived.relation_geometries USING gist (geom);
CREATE INDEX way_geometries_bbox_gist_idx ON derived.way_geometries USING gist (bbox);
CREATE INDEX relation_geometries_bbox_gist_idx ON derived.relation_geometries USING gist (bbox);
CREATE INDEX changesets_published_id_desc_idx ON core.changesets (id DESC) WHERE status = 'published';
CREATE INDEX draft_nodes_id_idx ON draft.nodes (id);
CREATE INDEX draft_ways_id_idx ON draft.ways (id);
CREATE INDEX draft_way_nodes_node_id_idx ON draft.way_nodes (node_id);
CREATE INDEX draft_relations_id_idx ON draft.relations (id);
CREATE INDEX draft_relation_members_member_idx ON draft.relation_members (member_type, member_id);
