-- Replace legacy username actor columns with stable user references in one
-- coordinated cutover.  The temporary columns make the backfill atomic.
CREATE TABLE core.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO core.users (username)
SELECT DISTINCT username
FROM (
  SELECT created_by AS username FROM core.changesets
  UNION SELECT created_by FROM core.nodes
  UNION SELECT updated_by FROM core.nodes
  UNION SELECT created_by FROM core.ways
  UNION SELECT updated_by FROM core.ways
  UNION SELECT created_by FROM core.relations
  UNION SELECT updated_by FROM core.relations
  UNION SELECT staged_by FROM draft.nodes
  UNION SELECT staged_by FROM draft.ways
  UNION SELECT staged_by FROM draft.relations
  UNION
    SELECT snapshot->>'createdBy'
    FROM history.node_versions
    WHERE jsonb_typeof(snapshot->'createdBy') = 'string'
  UNION
    SELECT snapshot->>'updatedBy'
    FROM history.node_versions
    WHERE jsonb_typeof(snapshot->'updatedBy') = 'string'
  UNION
    SELECT snapshot->>'createdBy'
    FROM history.way_versions
    WHERE jsonb_typeof(snapshot->'createdBy') = 'string'
  UNION
    SELECT snapshot->>'updatedBy'
    FROM history.way_versions
    WHERE jsonb_typeof(snapshot->'updatedBy') = 'string'
  UNION
    SELECT snapshot->>'createdBy'
    FROM history.relation_versions
    WHERE jsonb_typeof(snapshot->'createdBy') = 'string'
  UNION
    SELECT snapshot->>'updatedBy'
    FROM history.relation_versions
    WHERE jsonb_typeof(snapshot->'updatedBy') = 'string'
) actors
WHERE username IS NOT NULL;

ALTER TABLE core.changesets ADD COLUMN created_by_user_id bigint;
ALTER TABLE core.nodes ADD COLUMN created_by_user_id bigint, ADD COLUMN updated_by_user_id bigint;
ALTER TABLE core.ways ADD COLUMN created_by_user_id bigint, ADD COLUMN updated_by_user_id bigint;
ALTER TABLE core.relations ADD COLUMN created_by_user_id bigint, ADD COLUMN updated_by_user_id bigint;
ALTER TABLE draft.nodes ADD COLUMN staged_by_user_id bigint;
ALTER TABLE draft.ways ADD COLUMN staged_by_user_id bigint;
ALTER TABLE draft.relations ADD COLUMN staged_by_user_id bigint;

UPDATE core.changesets t SET created_by_user_id = u.id FROM core.users u WHERE u.username = t.created_by;
UPDATE core.nodes t SET created_by_user_id = u.id FROM core.users u WHERE u.username = t.created_by;
UPDATE core.nodes t SET updated_by_user_id = u.id FROM core.users u WHERE u.username = t.updated_by;
UPDATE core.ways t SET created_by_user_id = u.id FROM core.users u WHERE u.username = t.created_by;
UPDATE core.ways t SET updated_by_user_id = u.id FROM core.users u WHERE u.username = t.updated_by;
UPDATE core.relations t SET created_by_user_id = u.id FROM core.users u WHERE u.username = t.created_by;
UPDATE core.relations t SET updated_by_user_id = u.id FROM core.users u WHERE u.username = t.updated_by;
UPDATE draft.nodes t SET staged_by_user_id = u.id FROM core.users u WHERE u.username = t.staged_by;
UPDATE draft.ways t SET staged_by_user_id = u.id FROM core.users u WHERE u.username = t.staged_by;
UPDATE draft.relations t SET staged_by_user_id = u.id FROM core.users u WHERE u.username = t.staged_by;

ALTER TABLE core.changesets ALTER COLUMN created_by_user_id SET NOT NULL;
ALTER TABLE core.nodes ALTER COLUMN created_by_user_id SET NOT NULL, ALTER COLUMN updated_by_user_id SET NOT NULL;
ALTER TABLE core.ways ALTER COLUMN created_by_user_id SET NOT NULL, ALTER COLUMN updated_by_user_id SET NOT NULL;
ALTER TABLE core.relations ALTER COLUMN created_by_user_id SET NOT NULL, ALTER COLUMN updated_by_user_id SET NOT NULL;
ALTER TABLE draft.nodes ALTER COLUMN staged_by_user_id SET NOT NULL;
ALTER TABLE draft.ways ALTER COLUMN staged_by_user_id SET NOT NULL;
ALTER TABLE draft.relations ALTER COLUMN staged_by_user_id SET NOT NULL;

ALTER TABLE core.changesets ADD CONSTRAINT changesets_created_by_user_fk FOREIGN KEY (created_by_user_id) REFERENCES core.users(id);
ALTER TABLE core.nodes ADD CONSTRAINT nodes_created_by_user_fk FOREIGN KEY (created_by_user_id) REFERENCES core.users(id), ADD CONSTRAINT nodes_updated_by_user_fk FOREIGN KEY (updated_by_user_id) REFERENCES core.users(id);
ALTER TABLE core.ways ADD CONSTRAINT ways_created_by_user_fk FOREIGN KEY (created_by_user_id) REFERENCES core.users(id), ADD CONSTRAINT ways_updated_by_user_fk FOREIGN KEY (updated_by_user_id) REFERENCES core.users(id);
ALTER TABLE core.relations ADD CONSTRAINT relations_created_by_user_fk FOREIGN KEY (created_by_user_id) REFERENCES core.users(id), ADD CONSTRAINT relations_updated_by_user_fk FOREIGN KEY (updated_by_user_id) REFERENCES core.users(id);
ALTER TABLE draft.nodes ADD CONSTRAINT draft_nodes_staged_by_user_fk FOREIGN KEY (staged_by_user_id) REFERENCES core.users(id);
ALTER TABLE draft.ways ADD CONSTRAINT draft_ways_staged_by_user_fk FOREIGN KEY (staged_by_user_id) REFERENCES core.users(id);
ALTER TABLE draft.relations ADD CONSTRAINT draft_relations_staged_by_user_fk FOREIGN KEY (staged_by_user_id) REFERENCES core.users(id);

ALTER TABLE core.changesets DROP COLUMN created_by;
ALTER TABLE core.nodes DROP COLUMN created_by, DROP COLUMN updated_by;
ALTER TABLE core.ways DROP COLUMN created_by, DROP COLUMN updated_by;
ALTER TABLE core.relations DROP COLUMN created_by, DROP COLUMN updated_by;
ALTER TABLE draft.nodes DROP COLUMN staged_by;
ALTER TABLE draft.ways DROP COLUMN staged_by;
ALTER TABLE draft.relations DROP COLUMN staged_by;

-- History snapshots are immutable records, so retain each actor identity as
-- an ID while dropping the denormalized username.  Each key is converted
-- independently so partial snapshots are handled deterministically.
UPDATE history.node_versions h
SET snapshot = jsonb_set(h.snapshot - 'createdBy', '{createdByUserId}', to_jsonb(u.id), true)
FROM core.users u
WHERE jsonb_typeof(h.snapshot->'createdBy') = 'string'
  AND h.snapshot->>'createdBy' = u.username;
UPDATE history.node_versions h
SET snapshot = jsonb_set(h.snapshot - 'updatedBy', '{updatedByUserId}', to_jsonb(u.id), true)
FROM core.users u
WHERE jsonb_typeof(h.snapshot->'updatedBy') = 'string'
  AND h.snapshot->>'updatedBy' = u.username;
UPDATE history.way_versions h
SET snapshot = jsonb_set(h.snapshot - 'createdBy', '{createdByUserId}', to_jsonb(u.id), true)
FROM core.users u
WHERE jsonb_typeof(h.snapshot->'createdBy') = 'string'
  AND h.snapshot->>'createdBy' = u.username;
UPDATE history.way_versions h
SET snapshot = jsonb_set(h.snapshot - 'updatedBy', '{updatedByUserId}', to_jsonb(u.id), true)
FROM core.users u
WHERE jsonb_typeof(h.snapshot->'updatedBy') = 'string'
  AND h.snapshot->>'updatedBy' = u.username;
UPDATE history.relation_versions h
SET snapshot = jsonb_set(h.snapshot - 'createdBy', '{createdByUserId}', to_jsonb(u.id), true)
FROM core.users u
WHERE jsonb_typeof(h.snapshot->'createdBy') = 'string'
  AND h.snapshot->>'createdBy' = u.username;
UPDATE history.relation_versions h
SET snapshot = jsonb_set(h.snapshot - 'updatedBy', '{updatedByUserId}', to_jsonb(u.id), true)
FROM core.users u
WHERE jsonb_typeof(h.snapshot->'updatedBy') = 'string'
  AND h.snapshot->>'updatedBy' = u.username;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM history.node_versions
    WHERE snapshot ? 'createdBy' OR snapshot ? 'updatedBy'
      OR jsonb_typeof(snapshot->'createdByUserId') = 'string'
      OR jsonb_typeof(snapshot->'updatedByUserId') = 'string'
  ) OR EXISTS (
    SELECT 1 FROM history.way_versions
    WHERE snapshot ? 'createdBy' OR snapshot ? 'updatedBy'
      OR jsonb_typeof(snapshot->'createdByUserId') = 'string'
      OR jsonb_typeof(snapshot->'updatedByUserId') = 'string'
  ) OR EXISTS (
    SELECT 1 FROM history.relation_versions
    WHERE snapshot ? 'createdBy' OR snapshot ? 'updatedBy'
      OR jsonb_typeof(snapshot->'createdByUserId') = 'string'
      OR jsonb_typeof(snapshot->'updatedByUserId') = 'string'
  ) THEN
    RAISE EXCEPTION 'history actor migration left an unmapped legacy actor';
  END IF;
END $$;
