-- Worlds are public namespaces.  Existing installations are moved into one
-- stable namespace; an empty installation intentionally remains empty.
CREATE TABLE core.worlds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  created_by_user_id bigint NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT worlds_slug_format CHECK (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  CONSTRAINT worlds_slug_length CHECK (length(slug) BETWEEN 1 AND 64),
  CONSTRAINT worlds_name_length CHECK (length(btrim(name)) BETWEEN 1 AND 128),
  CONSTRAINT worlds_created_by_user_fk FOREIGN KEY (created_by_user_id)
    REFERENCES core.users(id)
);

CREATE OR REPLACE FUNCTION core.catlas_world_slug_immutable()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.slug IS DISTINCT FROM OLD.slug THEN
    RAISE EXCEPTION 'world slug is immutable';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER worlds_slug_immutable
  BEFORE UPDATE OF slug ON core.worlds
  FOR EACH ROW EXECUTE FUNCTION core.catlas_world_slug_immutable();

ALTER TABLE core.changesets ADD COLUMN world_id bigint;
ALTER TABLE core.nodes ADD COLUMN world_id bigint;
ALTER TABLE core.ways ADD COLUMN world_id bigint;
ALTER TABLE core.relations ADD COLUMN world_id bigint;
ALTER TABLE core.way_nodes ADD COLUMN world_id bigint;
ALTER TABLE core.relation_members ADD COLUMN world_id bigint;

DO $$
DECLARE first_row record;
DECLARE default_world bigint;
BEGIN
  SELECT created_by_user_id, created_at INTO first_row
    FROM core.changesets ORDER BY id LIMIT 1;
  IF FOUND THEN
    INSERT INTO core.worlds (slug, name, created_by_user_id, created_at)
      VALUES ('default', 'Default World', first_row.created_by_user_id, first_row.created_at)
      RETURNING id INTO default_world;
    UPDATE core.changesets SET world_id = default_world;
    UPDATE core.nodes n SET world_id = c.world_id
      FROM core.changesets c WHERE c.id = n.changeset_id;
    UPDATE core.ways w SET world_id = c.world_id
      FROM core.changesets c WHERE c.id = w.changeset_id;
    UPDATE core.relations r SET world_id = c.world_id
      FROM core.changesets c WHERE c.id = r.changeset_id;
    UPDATE core.way_nodes wn SET world_id = w.world_id
      FROM core.ways w WHERE w.id = wn.way_id;
    UPDATE core.relation_members rm SET world_id = r.world_id
      FROM core.relations r WHERE r.id = rm.relation_id;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM core.changesets WHERE world_id IS NULL)
     OR EXISTS (SELECT 1 FROM core.nodes WHERE world_id IS NULL)
     OR EXISTS (SELECT 1 FROM core.ways WHERE world_id IS NULL)
     OR EXISTS (SELECT 1 FROM core.relations WHERE world_id IS NULL) THEN
    RAISE EXCEPTION 'world backfill left a NULL world_id';
  END IF;
  IF EXISTS (SELECT 1 FROM core.way_nodes WHERE world_id IS NULL)
     OR EXISTS (SELECT 1 FROM core.relation_members WHERE world_id IS NULL) THEN
    RAISE EXCEPTION 'world backfill left a NULL child world_id';
  END IF;
  IF EXISTS (
    SELECT 1 FROM core.nodes n
    JOIN core.changesets created ON created.id = n.created_changeset_id
    JOIN core.changesets current ON current.id = n.changeset_id
    WHERE n.world_id <> created.world_id OR n.world_id <> current.world_id
  ) OR EXISTS (
    SELECT 1 FROM core.ways w
    JOIN core.changesets created ON created.id = w.created_changeset_id
    JOIN core.changesets current ON current.id = w.changeset_id
    WHERE w.world_id <> created.world_id OR w.world_id <> current.world_id
  ) OR EXISTS (
    SELECT 1 FROM core.relations r
    JOIN core.changesets created ON created.id = r.created_changeset_id
    JOIN core.changesets current ON current.id = r.changeset_id
    WHERE r.world_id <> created.world_id OR r.world_id <> current.world_id
  ) THEN
    RAISE EXCEPTION 'world backfill found an entity changeset mismatch';
  END IF;
  IF EXISTS (
    SELECT 1 FROM core.way_nodes wn
    JOIN core.ways w ON w.id = wn.way_id
    JOIN core.nodes n ON n.id = wn.node_id
    JOIN core.changesets c ON c.id = wn.changeset_id
    WHERE wn.world_id <> w.world_id OR wn.world_id <> n.world_id OR wn.world_id <> c.world_id
  ) OR EXISTS (
    SELECT 1 FROM core.relation_members rm
    JOIN core.relations r ON r.id = rm.relation_id
    JOIN core.changesets c ON c.id = rm.changeset_id
    WHERE rm.world_id <> r.world_id OR rm.world_id <> c.world_id
  ) THEN
    RAISE EXCEPTION 'world backfill found a child world mismatch';
  END IF;
  IF EXISTS (
    SELECT 1 FROM core.relation_members rm
    WHERE (rm.member_type = 'node' AND NOT EXISTS (
      SELECT 1 FROM core.nodes n WHERE n.id = rm.member_id AND n.world_id = rm.world_id
    )) OR (rm.member_type = 'way' AND NOT EXISTS (
      SELECT 1 FROM core.ways w WHERE w.id = rm.member_id AND w.world_id = rm.world_id
    )) OR (rm.member_type = 'relation' AND NOT EXISTS (
      SELECT 1 FROM core.relations r WHERE r.id = rm.member_id AND r.world_id = rm.world_id
    ))
  ) THEN
    RAISE EXCEPTION 'world backfill found a relation member mismatch';
  END IF;
END $$;

ALTER TABLE core.changesets ALTER COLUMN world_id SET NOT NULL;
ALTER TABLE core.nodes ALTER COLUMN world_id SET NOT NULL;
ALTER TABLE core.ways ALTER COLUMN world_id SET NOT NULL;
ALTER TABLE core.relations ALTER COLUMN world_id SET NOT NULL;
ALTER TABLE core.way_nodes ALTER COLUMN world_id SET NOT NULL;
ALTER TABLE core.relation_members ALTER COLUMN world_id SET NOT NULL;

ALTER TABLE core.nodes ADD CONSTRAINT nodes_id_world_unique UNIQUE (id, world_id);
ALTER TABLE core.ways ADD CONSTRAINT ways_id_world_unique UNIQUE (id, world_id);
ALTER TABLE core.relations ADD CONSTRAINT relations_id_world_unique UNIQUE (id, world_id);

ALTER TABLE core.changesets ADD CONSTRAINT changesets_world_unique UNIQUE (id, world_id);
ALTER TABLE core.changesets ADD CONSTRAINT changesets_world_fk
  FOREIGN KEY (world_id) REFERENCES core.worlds(id);
ALTER TABLE core.nodes ADD CONSTRAINT nodes_created_world_fk
  FOREIGN KEY (created_changeset_id, world_id) REFERENCES core.changesets(id, world_id);
ALTER TABLE core.nodes ADD CONSTRAINT nodes_current_world_fk
  FOREIGN KEY (changeset_id, world_id) REFERENCES core.changesets(id, world_id);
ALTER TABLE core.ways ADD CONSTRAINT ways_created_world_fk
  FOREIGN KEY (created_changeset_id, world_id) REFERENCES core.changesets(id, world_id);
ALTER TABLE core.ways ADD CONSTRAINT ways_current_world_fk
  FOREIGN KEY (changeset_id, world_id) REFERENCES core.changesets(id, world_id);
ALTER TABLE core.relations ADD CONSTRAINT relations_created_world_fk
  FOREIGN KEY (created_changeset_id, world_id) REFERENCES core.changesets(id, world_id);
ALTER TABLE core.relations ADD CONSTRAINT relations_current_world_fk
  FOREIGN KEY (changeset_id, world_id) REFERENCES core.changesets(id, world_id);
ALTER TABLE core.way_nodes ADD CONSTRAINT way_nodes_way_world_fk
  FOREIGN KEY (way_id, world_id) REFERENCES core.ways(id, world_id);
ALTER TABLE core.way_nodes ADD CONSTRAINT way_nodes_node_world_fk
  FOREIGN KEY (node_id, world_id) REFERENCES core.nodes(id, world_id);
ALTER TABLE core.way_nodes ADD CONSTRAINT way_nodes_changeset_world_fk
  FOREIGN KEY (changeset_id, world_id) REFERENCES core.changesets(id, world_id);
ALTER TABLE core.relation_members ADD CONSTRAINT relation_members_relation_world_fk
  FOREIGN KEY (relation_id, world_id) REFERENCES core.relations(id, world_id);
ALTER TABLE core.relation_members ADD CONSTRAINT relation_members_changeset_world_fk
  FOREIGN KEY (changeset_id, world_id) REFERENCES core.changesets(id, world_id);

CREATE OR REPLACE FUNCTION core.catlas_relation_member_same_world()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF (NEW.member_type = 'node' AND NOT EXISTS (
      SELECT 1 FROM core.nodes WHERE id = NEW.member_id AND world_id = NEW.world_id
    )) OR (NEW.member_type = 'way' AND NOT EXISTS (
      SELECT 1 FROM core.ways WHERE id = NEW.member_id AND world_id = NEW.world_id
    )) OR (NEW.member_type = 'relation' AND NOT EXISTS (
      SELECT 1 FROM core.relations WHERE id = NEW.member_id AND world_id = NEW.world_id
    )) THEN
    RAISE EXCEPTION 'relation member belongs to a different world';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER relation_members_same_world
  BEFORE INSERT OR UPDATE ON core.relation_members
  FOR EACH ROW EXECUTE FUNCTION core.catlas_relation_member_same_world();

CREATE INDEX changesets_world_status_id_idx
  ON core.changesets (world_id, status, id DESC);
CREATE INDEX nodes_world_id_idx ON core.nodes (world_id, id);
CREATE INDEX ways_world_id_idx ON core.ways (world_id, id);
CREATE INDEX relations_world_id_idx ON core.relations (world_id, id);
